hosts: [
  { host_ip: "200.200.200.200", host_name: "oracledb"},
  { host_ip: "200.200.200.201", host_name: "mysqldb"},
  { host_ip: "200.200.200.202", host_name: "postgrsqldb"},
  { host_ip: "200.200.200.203", host_name: "mssql"},
  { host_ip: "200.200.200.204", host_name: "mongodb"}
]
parameters: [
  { name: "vm.max_map_count", value: "262144"},
  { name: "vm.overcommit_memory", value: "1"},
  { name: "vm.swappiness", value: "0"},
  { name: "net.core.somaxconn", value: "65535"},
  { name: "net.ipv4.tcp_max_syn_backlog", value: "65535"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" }
  ]
