hosts: [
  { host_ip: "192.16.35.10", host_name: "k8s-n1"},
  { host_ip: "192.16.35.11", host_name: "k8s-n2"},  
  { host_ip: "192.16.35.12", host_name: "k8s-n3"}, 
  { host_ip: "192.16.35.13", host_name: "k8s-n4"}, 
  { host_ip: "192.16.35.14", host_name: "k8s-m1"}  
]
parameters: [
  { name: "vm.max_map_count", value: "262144"},
  { name: "vm.overcommit_memory", value: "1"},
  { name: "vm.swappiness", value: "0"},
  { name: "net.core.somaxconn", value: "65535"},
  { name: "net.ipv4.tcp_max_syn_backlog", value: "65535"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" }
  ]
