- name:  set-timezone Asia/Taipei
  shell: timedatectl set-timezone Asia/Taipei
  ignore_errors: yes
  tags:  [common]
  
- name:  locale-gen zh_TW
  shell: sudo locale-gen zh_TW;sudo locale-gen zh_TW.UTF-8 ;sudo dpkg-reconfigure locales;sudo update-locale LANG="zh_TW.UTF-8" LC_ALL="zh_TW.UTF-8" ; 
  ignore_errors: yes 
  tags:  [common]

- name:  localedef -f UTF-8 -i zh_TW  zh_TW.UTF-8
  shell: localedef -f UTF-8 -i zh_TW  zh_TW.UTF-8
  ignore_errors: yes 
  tags:  [common]


- name: JQ is present
  apt:
    name: jq
    force: yes
  ignore_errors: yes
  tags: [common]

- name: ipvsadm is present
  apt:
    name: ipvsadm
    state: latest 
  tags: [common]

- name:  Make sure that the ip_vs kernel module is loaded
  shell: ipvsadm  -ln
  ignore_errors: yes
  become: yes
  become_method: sudo
  tags:  [common]

- name: open-iscsi is present
  apt:
    name: open-iscsi
    state: latest   
  tags: [common]

- name: Enable service open-iscsi, and not touch the state
  service:
    name: open-iscsi
    enabled: yes
  tags: [common]

- name: open-iscsi service is started
  service:
      name: open-iscsi
      state: started
  tags: [common] 

- name: Services are not running
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items: "{{ obsolete_services }}"
  tags: [common]

